name : Docker Pipeline

on: 
    push:
        branches: [ "main" ]
    

jobs: 
    docker:
        name: docker
        runs-on: ubuntu-latest
        steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: login dockerhub