name: Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Change these variables according to your Docker Hub username and image name
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  IMAGE_NAME: go-docker-app
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 1: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Step 2: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      # Step 3: Tag Docker image
      - name: Tag Docker image
        run: |
          docker tag myapp:latest austinbale667/myapp:latest

      # Step 4: Push to Docker Hub
      - name: Push to Docker Hub
        run: |
          docker push austinbale667/myapp:latest

      # Step 5: Run Docker container (for testing)
      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 austinbale667/myapp:latest
          # Wait for container to start
          sleep 10
          # Test if the container is running
          curl http://localhost:8080 || exit 1